app:
  name: fast-food-api
  image:
    repository: danieltezolin/fast-food-api
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

env:
  # Database
  DB_HOST: "your-rds-endpoint.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "soatfastfood"
  DB_USER: "app_user"
  
  # Application
  PORT: "8080"
  GIN_MODE: "release"
  ENVIRONMENT: "production"

secrets:
  DB_PASSWORD: "eW91cl9iYXNlNjRfZW5jb2RlZF9wYXNzd29yZA=="
  
  ACCESSTOKEN: "eW91cl9tZXJjYWRvcGFnb190b2tlbl9oZXJl"

namespace:
  create: true
  name: fast-food

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

serviceAccount:
  create: true
  annotations: {}
  name: ""
