apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fast-food.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fast-food.labels" . | nindent 4 }}
data:
  # Database Configuration
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  
  # Application Configuration
  PORT: {{ .Values.env.PORT | quote }}
  GIN_MODE: {{ .Values.env.GIN_MODE | quote }}
  
  # Environment
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fast-food.fullname" . }}-mysql-init
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fast-food.mysql.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS customers (
        id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        first_name  VARCHAR(100),
        last_name   VARCHAR(100),
        cpf         VARCHAR(14) UNIQUE,
        email       VARCHAR(255) UNIQUE,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS orders (
        id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        customer_id BIGINT UNSIGNED NULL REFERENCES customers(id),
        cpf         VARCHAR(14) NULL,
        status      ENUM('awaiting_payment', 'received', 'in_progress', 'ready', 'completed', 'cancelled'),
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS products (
        id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name        VARCHAR(100) NOT NULL,
        description TEXT,
        price       FLOAT NOT NULL,
        category    ENUM('snack', 'side', 'drink', 'dessert'),
        image_url   VARCHAR(255) NULL,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS order_items (
        id           BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        order_id     BIGINT UNSIGNED NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        product_id   BIGINT UNSIGNED NOT NULL REFERENCES products(id),
        quantity     INTEGER NOT NULL DEFAULT 1,
        price        FLOAT NOT NULL,
        created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS payments (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        order_id BIGINT UNSIGNED NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        amount DECIMAL(10,2) NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        payment_method VARCHAR(50) NOT NULL,
        transaction_id VARCHAR(255) DEFAULT '',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );