apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fast-food.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fast-food.labels" . | nindent 4 }}
data:
  # Database Configuration
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  
  # Application Configuration
  PORT: {{ .Values.env.PORT | quote }}
  GIN_MODE: {{ .Values.env.GIN_MODE | quote }}
  
  # Environment
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
